config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posters#index'

  shallow do
    resources :posters do
      member do
        patch :like
        patch :dislike
        put :in_favor
        put :oppose
      end
      resources :stands do
        resources :comments
        member do
          put :in_favor
          put :down
        end
      end
    end
  end
  resources :supports
end

app/models/poster.rb
class Poster < ActiveRecord::Base
  belongs_to :user
  belongs_to :source
  has_many :stands
  has_many :versions, through: :stands
  has_many :comments, through: :versions
  has_many :relatings, class_name: Relatable, foreign_key: :related_id
  has_many :relateds, class_name: Relatable, foreign_key: :relating_id
  has_many :relating_posters, through: :relatings, source: :relating
  has_many :related_posters, through: :relateds, source: :related
  acts_as_votable
  accepts_nested_attributes_for :relatings

  validates :question, presence: true

  default_scope { order(cached_votes_score: :desc).order(created_at: :desc) }
  scope :by_tag, ->(tag) { where("tags like ?", "%#{tag}%") }

  def has_stand_of?(user)
    stands.exists?(user: user)
  end

  def stand_of(user)
    stands.find_by(user: user)
  end

  def relatable_posters
    (relating_posters.all + related_posters.all).uniq
  end

  def url
    self_or_source(:url)
  end

  def title
    self_or_source(:title)
  end

  def description
    self_or_source(:description)
  end

  def image
    self_or_source(:image)
  end

  def same_sourced_posters
    source.posters.where.not(id: self)
  end

  def persisted_stands(choice = nil)
    result = stands.latest.reject(&:new_record?)
    result = result.select(&:"#{choice}?".to_sym) unless choice.nil?
    result
  end

  def likable_by(user)
    return false if user.nil?
    !user.liked?(self)
  end

  def dislikable_by(user)
    return false if user.nil?
    !user.disliked?(self)
  end

  def self.tags
    self.all.map(&:tags).compact.join(' ').split.uniq
  end

  private

  def self_or_source(field)
    read_attribute(field) || source.try(field)
  end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  include SlackNotifing

  def index
    @posters = Poster.all
    @posters = @posters.by_tag(params[:tag]) if params[:tag].present?
  end

  def new
    @poster = Poster.new
    if params[:source_id].present?
      @source = Source.find params[:source_id]
    end
  end

  def show
    @poster = Poster.find(params[:id])
    if params[:auth].present?
      session[:user_return_to] = poster_path(@poster)
      redirect_to new_user_session_path and return
    end

    has_stand = (user_signed_in? and @poster.has_stand_of?(current_user))
    @current_user_stand = (has_stand ? @poster.stand_of(current_user) : @poster.stands.build)
  end

  def create
    @poster = Poster.new(create_params)
    unless @poster.source.present?
      @poster.source = Source.find_or_initialize_by(url: @poster.url) do |s|
        s.url = @poster.url
      end
    end
    @poster.user = current_user
    @poster.save

    if @poster.errors.any?
      flash[:error] = @poster.errors.full_messages.to_sentence
      redirect_to :back and return
    else
      slack(@poster)
      redirect_to @poster
    end
  end

  def in_favor
    @poster = Poster.find(params[:id])
    @stand = @poster.stand_of(current_user) || @poster.stands.build
    @stand.versions.build(choice: 'in_favor')
    @stand.user = current_user if @stand.user.nil?
    @stand.save

    redirect_to @poster
  end

  def oppose
    @poster = Poster.find(params[:id])
    @stand = @poster.stand_of(current_user) || @poster.stands.build
    @stand.versions.build(choice: 'oppose')
    @stand.user = current_user if @stand.user.nil?
    @stand.save

    redirect_to @poster
  end

  def like
    @poster = Poster.find(params[:id])
    current_user.likes @poster
    redirect_to root_path
  end

  def dislike
    @poster = Poster.find(params[:id])
    current_user.dislikes @poster
    redirect_to root_path
  end
  private

  def create_params
    params.require(:poster).permit(:source_id, :url, :tags, :question, relatings_attributes: [ :relating_id ] )
  end
end

app/views/posters/_poster.html.haml
.panel.panel-default
  .panel-heading
    %span.fa-stack.pull-left
      = link_to like_poster_path(poster), method: :patch, class: "btn btn-success btn-xs #{'disabled' unless poster.likable_by(current_user)}" do
        %i.fa.fa-chevron-up
          = poster.get_likes.size
      = link_to dislike_poster_path(poster), method: :patch, class: "btn btn-danger btn-xs #{'disabled' unless poster.dislikable_by(current_user)}" do
        %i.fa.fa-chevron-down
          = poster.get_dislikes.size
    %h4
      &nbsp;
      = link_to_if !current_page?(controller: :posters, action: :show, id: poster), poster.title, poster
      %small= link_to truncate(poster.url), poster.url

  - if poster.description.present? or !current_page?(controller: :posters, action: :show, id: poster)
    .panel-body
      - if poster.description.present?
        %p.lead
          = poster.description
          = link_to "[더보기]", poster.url

      - unless current_page?(controller: :posters, action: :show, id: poster)
        .text-center
          = link_to poster do
            %h4
              .label.label-info
                %i.fa.fa-users
                = poster.persisted_stands.count

  .panel-footer.text-muted
    %ul.list-inline(style='margin-bottom: 0px;')
      %li
        %i.fa.fa-user
        = poster.user.email
        님이 붙인 대자보입니다.
      - if poster.tags.present?
        %li
          %i.fa.fa-tag
          - poster.tags.split.each do |tag|
            = link_to "##{tag}", posters_path(tag: tag)

app/views/posters/index.html.haml
%section.breadcrumb-wrapper
  %ol.breadcrumb
    %li= link_to 'Home', root_path
    - if params[:tag].present?
      %li.active ##{params[:tag]}

- if Poster.tags.any? and !params[:tag].present?
  %section.bs-component
    .jumbotron
      %h4.text-center
        - Poster.tags.each do |tag|
          %strong= link_to "##{tag}", posters_path(tag: tag)

%section
  - @posters.each do |poster|
    = render poster

app/views/posters/new.html.haml
.bs-component
  .jumbotron
    %h2 포스터 시작하기
    .well.bs-component
      = form_for @poster do |f|
        %fieldset
          .form-group
            = f.label :url do
              링크 주소
            - if @source.present?
              = f.hidden_field :source_id, value: @source.id
              = link_to @source.url, @source.url
            - else
              .text-muted http://까지 넣어주세요.
              = f.text_field :url, class: 'form-control'
          / .form-group
          /   = f.label :question do
          /     의견
          /   .text-muted 위에 링크에 대한 의견이나 토론 주제를 써주세요.
          /   = f.text_area :question, class: 'form-control'
          = f.hidden_field :question, value: 'none'
          .form-group
            = f.label :tags, '태그'
            .text-muted 위 링크와 연관된 태그를 넣어 주세요. 여러 태그를 넣을 때는 빈 공백을 넣어 주세요.
            = f.text_field :tags, class: 'form-control'
          - if params[:relating_poster_id]
            = f.fields_for :relatings, @poster.relatings.build do |f_relating|
              = f_relating.hidden_field :relating_id, value: params[:relating_poster_id]
          .form-group
            = f.submit class: 'btn btn-primary'

app/views/posters/show.html.haml
%section.breadcrumb-wrapper
  %ol.breadcrumb
    %li= link_to 'Home', root_path
    %li.active= @poster.title

%section
  = render @poster

%section
  - if user_signed_in?
    .well
      %h4
        - if @poster.has_stand_of?(current_user)
          .pull-right
            %small
              = link_to '내 의견 보기 >', @poster.stand_of(current_user)
          .label.label-info
            %i.fa.fa-users
            사람들의 의견
            = @poster.persisted_stands.count

  - if user_signed_in?
    - stands = @poster.persisted_stands.in_groups_of(3)
    .row
      .col-md-4
        - stands.map(&:first).compact.each do |stand|
          = render stand
      .col-md-4
        - stands.map(&:second).compact.each do |stand|
          = render stand
      .col-md-4
        - stands.map(&:last).compact.each do |stand|
          = render stand
    - unless @poster.has_stand_of?(current_user)
      %p
        #{current_user.email}님의 의견을 밝혀 주세요.
        = render partial: 'stands/form', locals: {stand: @current_user_stand}
  - else
    %p 다른 사람들의 의견을 살펴 보시기 전에 먼저 로그인해 주세요.
    = link_to 'Log in', poster_path(@poster, auth: 1), class: 'btn btn-default'


%hr

/ %section
/   %h5
/     %i.glyphicon.glyphicon-random
/     같은 링크, 다른 토론 주제
/     = link_to '다른 주제로 토론하기', new_poster_path(source_id: @poster.source), class: 'btn btn-sm btn-default'
/   %ul
/   - @poster.same_sourced_posters.each do |the_other_poster|
/     - unless the_other_poster == @poster
/       %li
/         = link_to the_other_poster.question, the_other_poster
/         %span.text-muted
/           \-
/           %i.glyphicon.glyphicon-user
/           = the_other_poster.user.email

%section
  %h5
    %i.glyphicon.glyphicon-link
    연결 대자보
    = link_to '연결 대자보 만들기', new_poster_path(relating_poster_id: @poster), class: 'btn btn-sm btn-default'
  %ul
  - @poster.relatable_posters.each do |relatable|
    %li
      = link_to relatable.title, relatable
      %span.text-muted
        \-
        %i.glyphicon.glyphicon-user
        = relatable.user.email