config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posters#index'

  shallow do
    resources :posters do
      member do
        patch :like
        patch :dislike
        put :in_favor
        put :oppose
      end
      resources :stands do
        resources :comments
        member do
          put :in_favor
          put :down
        end
      end
    end
  end
  resources :supports
end

app/models/stand.rb
class Stand < ActiveRecord::Base
  include Choicable

  belongs_to :user
  belongs_to :poster
  has_many :versions
  has_many :comments do
    def persisted
      collect{ |comment| comment if comment.persisted? }
    end
  end
  has_many :supports
  has_many :supporteds, class_name: Support, foreign_key: :target_id do
    def by_user(user)
      joins(:stand).where(stands: {user_id: user})
    end
  end

  accepts_nested_attributes_for :versions

  scope :latest, ->{ order(updated_at: :desc) }

  def current_version
    versions.offset(0).last
  end

  def previous_version
    versions.offset(1).last
  end

  def has_changes?
    versions.count > 1
  end

  def supported?(user)
    supporteds.by_user(user).exists?
  end

  def supported(user)
    supporteds.by_user(user).first
  end

  def reason
    current_version.reason
  end

  def choice
    current_version.choice
  end

  def statuses
    result = comments.persisted + versions + supports + supporteds
    result.compact.sort_by!(&:created_at).reverse
  end
end

app/controllers/stands_controller.rb
class StandsController < ApplicationController
  include SlackNotifing

  def show
    @stand = Stand.find params[:id]
    @poster = @stand.poster

    if !user_signed_in? or !@poster.has_stand_of? current_user
      redirect_to @poster and return
    end
  end

  def edit
    @stand = Stand.find(params[:id])
  end

  def oppose
  end

  def create
    @poster = Poster.find(params[:poster_id])
    @stand = @poster.stands.build(create_params)
    @stand.user = current_user

    @stand.save

    if @stand.errors.any?
      flash[:error] = @stand.errors.full_messages.to_sentence
    else
      slack(@stand)
    end
    redirect_to @stand.poster
  end

  def update
    @stand = Stand.find(params[:id])
    previous = @stand.current_version

    version_params = update_params[:versions_attributes]['0']
    unless previous.same? version_params
      @stand.assign_attributes(update_params)
      @stand.touch
      @version = @stand.versions.last
      @version.previous = previous
    end

    @stand.save

    errors = []
    errors << @stand.errors.full_messages.to_sentence if @stand.errors.any?
    errors << @version.errors.full_messages.to_sentence if @version.present? and @version.errors.any?
    flash[:error] = errors.join

    unless errors.any?
      slack(@stand)
    end

    redirect_to @stand.poster
  end

  private

  def create_params
    params.require(:stand).permit(versions_attributes: [:choice, :reason])
  end

  def update_params
    params.require(:stand).permit(versions_attributes: [:choice, :reason])
  end
end

app/views/stands/_form.html.haml
= form_for [(stand.poster unless stand.persisted?), stand] do |f|
  = render partial: 'shared/error_messages', locals: { object: stand }
  = f.fields_for :versions, stand.versions.build do |f_version|
    = render partial: 'versions/form', locals: {previous_version: stand.current_version, f: f_version}

app/views/stands/_stand.html.haml
.panel.panel-default{id: dom_id(stand)}
  .panel-heading
    .text-muted.pull-right
      - if current_user == stand.user
        = link_to '의견 다듬기', edit_stand_path(stand), class: 'btn btn-default btn-xs'
      - else
        - if !stand.supported?(current_user)
          = link_to supports_path(target_id: stand), method: :post, class: 'btn btn-default btn-xs' do
            지지하기
            %span.badge= stand.supporteds.count
        - else
          = link_to support_path(stand.supported(current_user)), method: :delete, class: 'btn btn-default btn-xs' do
            지지철회
            %span.badge= stand.supporteds.count
    / - if stand.current_version.change_choice?
    /   %span.label(class="label-#{stand.previous_version.choice}")= stand.previous_version.choice
    /   %i.glyphicon.glyphicon-arrow-right
    / %span.label(class="label-#{stand.choice}")= stand.choice
    .user
      %i.glyphicon.glyphicon-user
      = stand.user.email

  .panel-body
    = stand.reason

    - if stand.supports.any?
      %h6
        %i.glyphicon.glyphicon-hand-down
        아래 의견을 지지합니다.
      %ul
        - stand.supports.each do |support|
          %li
            = link_to support.target, style: 'text-decoration: none' do
              / %span.label(class="label-#{support.target.choice}")= support.target.choice
              - if support.target.reason.present?
                "#{truncate(support.target.reason)}"
              %span.text-muted
                %i.glyphicon.glyphicon-user
                = support.target.user.email

  %ul.list-group
    %li.list-group-item
      = render partial: 'comments/form', locals: { stand: stand }
    - if current_page?(controller: :stands, action: :show, id: stand)
      - stand.statuses.each do |status|
        = render partial: status, locals: { stand: stand }
    - else
      - stand.comments.latest.persisted.first(2).each do |status|
        - if status.present?
          = render partial: status, locals: { stand: stand }

  - unless current_page?(controller: :stands, action: :show, id: stand)
    .panel-footer
      = link_to '자세히 보기>>', stand

app/views/stands/edit.html.haml
%h4 의견
= render partial: 'stands/form', locals: {stand: @stand}

app/views/stands/show.html.haml
%section.breadcrumb-wrapper
  %ol.breadcrumb
    %li= link_to 'Home', root_path
    %li= link_to @poster.title, @poster
    %li.active
      = @stand.user.email
      의 의견

%section
  = render @poster

%section
  = render @stand